### ISSUE TITLE
Not responding to time request from CM11

### ISSUE THREAD

**Issue by mrpink76** [AlanDThiessen/x10-cm11-adapter#3]
Tried getting an old CM11 device working with Mozilla IOT gateway.

Unfortunately it didn't work.

After some investigation it seems like my device is sending the byte 0xa5 every second and according to "http://wanderingsamurai.net/electronics/cm11a-x10-protocol-document" this seems to be a time request which the computer must respond to before normal operation can continue.

Is this something that might be implemented sometime in the near future?

If not do you have any pointers on how I can try to fix it myself? 

Thanks in advance

**Comment by AlanDThiessen** [comment]
Thanks for reporting this.  I thought this case was handled.  This adapter uses the [CM11-JS node module](https://github.com/AlanDThiessen/cm11a-js) I developed.  It should be handled by the [SetClock transaction](https://github.com/AlanDThiessen/cm11a-js/blob/master/src/SetClock.js).  All that is necessary (according to the documentation I've found) is to send the header--the time is not required.

I'll try to take a look at it in the next few days.  Unfortunately, my CM11A no longer responds to serial commands, so I don't really have a way to test anymore.  There may be a way to get my CM11A working again.  Meanwhile, If I make changes, are you able to test them?

**Comment by mrpink76** [comment]
Of course! Looking forward to it :)

**Comment by AlanDThiessen** [comment]
Good news: my CM11A is working.  I fixed a bug in the cm11a-js node script when it was attempting to handle the power fail scenario.  This addon is now working on my Mozilla IoT gateway.  

To test this update on you gateway:

1. ssh to your Raspberry Pi.
2. Clone this repository into ~/.mozilla-iot/addons/. (Afterwards, you should see ~/.mozilla-iot/addons/x10-cm11-adapter/.)
3. Update the NPM dependencies from the x10-cm11-adapter directory:
` pi@gateway:~/.mozilla-iot/addons/x10-cm11-adapter/ $ npm install`
4. Then restart your Mozilla IoT gateway:
`$ sudo systemctl restart mozilla-iot-gateway.service`

Please let me know how it goes.  :-)

**Comment by mrpink76** [comment]
Just tried to follow your instructions.

1. Logged in using the pi user
2. Just as a note I had to create the directory "addons" under ".mozilla-iot" since it was not present
3. Cloned the x10-cm11-adapter
4. Installed the npm modules
5. When browsing to my iot-gateway I found that the x10-cm11-adapter version still was 0.2.1 so I feel like the new version is not getting picked up.

**Comment by AlanDThiessen** [comment]
Could you please ensure the directory you cloned 1) has "version": "0.3.1" in the package.json file; 2) has a .git subdirectory;  and 3) that you restarted your gateway (step 4 above)?

If this does not load the updated version, then I will just publish the updated version and verify it solves your problem when you get the update.

**Comment by mrpink76** [comment]
My bad!

I seemed to have cloned the repo to "~/mozilla-iot/addons" instead of "~/.mozilla-iot/addons" :(

When I cloned to the correct directory ("~/.mozilla-iot/addons") the correct version was reported by mozilla iot gateway.

It doesn't seem to work though. Below you can see part of the log that reports receiving 165 (0xa5).

I hope this might shed some light om the problem :)

```
2018-10-29 18:40:33.427 Not checking SHA256SUMS file for x10-cm11-adapter since a .git directory was detected
2018-10-29 18:40:33.454 Loading add-on: x10-cm11-adapter
2018-10-29 18:40:34.374 x10-cm11: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2018-10-29 18:40:34.421 x10-cm11: Loading add-on for x10-cm11-adapter from /home/pi/.mozilla-iot/addons/x10-cm11-adapter
2018-10-29 18:40:34.782 x10-cm11: CM11A: Opening /dev/ttyUSB1
2018-10-29 18:40:34.793 x10-cm11: [ { name: 'on',
2018-10-29 18:40:34.793 x10-cm11:     value: false,
2018-10-29 18:40:34.794 x10-cm11:     metadata: { '@type': 'OnOffProperty', label: 'On/Off', type: 'boolean' } } ]
2018-10-29 18:40:34.795 x10-cm11: CM11A Device Added: X10 Appliance Module (A2) with address A2
2018-10-29 18:40:36.789 x10-cm11: CM11A Rx: 165
2018-10-29 18:40:36.792 x10-cm11: Unhandled Rejection
2018-10-29 18:40:39.459 PropertyProxy: setProperty property: on for: x10-A2 to value: true
2018-10-29 18:40:39.465 x10-cm11: CM11A Property changed for A2: on = true
2018-10-29 18:40:39.469 x10-cm11: CM11A Tx: 4,110
2018-10-29 18:40:40.477 x10-cm11: CM11A Tx: 4,110
2018-10-29 18:40:40.979 PropertyProxy: setProperty property: on for: x10-A2 to value: false
2018-10-29 18:40:40.982 x10-cm11: CM11A Property changed for A2: on = false
2018-10-29 18:40:41.478 x10-cm11: CM11A Tx: 4,110
2018-10-29 18:40:42.480 x10-cm11: CM11A Tx: 4,110
```

**Comment by AlanDThiessen** [comment]
Interesting.  "Unhandled Rejection" indicates a JavaScript Promise is getting rejected, but the rejection is not handled.

I decided to do a clean reinstall of the module in ~/.mozilla-iot/addons/ to see if I could duplicate your results.  I pulled my CM11A from the wall (batteries are not installed), and restarted the server.  I get a different result: the addon responds to the 165 (0xA5) with a 155 (0x9B) (log snipped below).  I have seven devices installed, but the timing does not look much different.  

Curious, would you run the following command from the x10-cm11-adapter directory and tell me which version of cm11a-js is reported?

`pi@gateway:~/.mozilla-iot/addons/x10-cm11-adapter $ npm list cm11a-js`

You should see something like this:

```
x10-cm11-adapter@0.3.1 /home/pi/.mozilla-iot/addons/x10-cm11-adapter
└── cm11a-js@0.4.2 
```
If you do see version 0.4.2, we may need to add some logging in the cm11a-js module to see which promise is getting rejected and where.

Meanwhile, I'll continue looking to see where the promise could be rejected.

Here's my log:

```
2018-10-27 17:36:50.264 Not checking SHA256SUMS file for x10-cm11-adapter since a .git directory was detected
2018-10-27 17:36:53.267 Loading add-on: x10-cm11-adapter
2018-10-27 17:36:55.239 x10-cm11: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2018-10-27 17:36:55.525 x10-cm11: Loading add-on for x10-cm11-adapter from /home/pi/.mozilla-iot/addons/x10-cm11-adapter
2018-10-27 17:36:56.231 x10-cm11: CM11A: Opening /dev/ttyUSB1
... [log adding 7 X10 devices] ...
2018-10-27 17:36:58.091 x10-cm11: CM11A Rx: 165
2018-10-27 17:36:58.095 x10-cm11: CM11A Tx: 155

```

**Comment by mrpink76** [comment]
Just tried the command you suggested and it reports the wrong cm11a-js version.

```
pi@gateway:~/.mozilla-iot/addons/x10-cm11-adapter $ npm list cm11a-js
x10-cm11-adapter@0.3.1 /home/pi/.mozilla-iot/addons/x10-cm11-adapter
└── cm11a-js@0.3.2  invalid

npm ERR! invalid: cm11a-js@0.3.2 /home/pi/.mozilla-iot/addons/x10-cm11-adapter/node_modules/cm11a-js
```

I tried to re-run "npm install" and now the correct version is displayed and everyhing seems to work! :D 
(I managed to switch a lamp on and off!)

```
pi@gateway:~/.mozilla-iot/addons/x10-cm11-adapter $ npm list cm11a-js
x10-cm11-adapter@0.3.1 /home/pi/.mozilla-iot/addons/x10-cm11-adapter
└── cm11a-js@0.4.2
```

Will test more tonight!

**Comment by AlanDThiessen** [comment]
Great!  I'm not sure why it didn't install the correct version of the dependencies the first time, but I'm glad you were able to upgrade to the latest version and that it solves your problem.  :-)

I've published the updated version with Mozilla IoT, and they have already pulled it in.  In order to get the update, I believe all you should need to do is remove the `.git` sub-directory from `~/.mozilla-iot/addons/x10-cm11-adapter/`.

I did a full wipe of the addon (`rm -rf ~/.mozilla-iot/addons/x10-cm11-adapter`) and then re-installed it through the Settings -> Addons menu.  None of my settings were lost in the process.  So, it you want to ensure you're fully back on release train, you could do a full wipe as well.

Thank you for your help testing this fix!  If there's anything else I can help with, or if you have any suggestions or feature requests with the X10 add-on, please let me know!  :-)

**Comment by mrpink76** [comment]
Big thanks for helping me getting my X10 setup working again!

Everything works great now and so does my log.

Gonna close the issue :)
